name: Compile & Formatting Check

on:
  pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: "! contains(github.event.pull_request.labels.*.name, 'documentation')"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', 'project/**') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
      - name: Compile and Check Formatting
        run: sbt test:compile scalafmtCheckAll
